package com.resort.platform.audit;

/** Ações auditadas (SPEC §19). Espelha o CHECK de {@code audit_logs.action}. */
public enum AuditAction {
    LOGIN, LOGIN_FAILED, LOGOUT, PASSWORD_CHANGED, PASSWORD_RESET,
    USER_CREATED, USER_UPDATED, USER_STATUS_CHANGED,
    LEAD_CREATED, LEAD_UPDATED, LEAD_STATUS_CHANGED, LEAD_ASSIGNED, LEAD_IMPORTED,
    VISIT_CREATED, VISIT_UPDATED, VISIT_RESCHEDULED, VISIT_CANCELLED, VISIT_NO_SHOW,
    INVITATION_CREATED, INVITATION_REISSUED, INVITATION_CANCELLED, INVITATION_EXPIRED,
    ACCESS_VALIDATED, ACCESS_DENIED,
    EXPORT_GENERATED
}
